# Generated by Django 6.0.6 on 2026-07-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketRegime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("symbol", models.CharField(default="XAUUSD", max_length=20)),
                (
                    "current_regime",
                    models.CharField(
                        choices=[
                            ("TRENDING_UP", "Trending Up"),
                            ("TRENDING_DOWN", "Trending Down"),
                            ("RANGING", "Ranging/Bound"),
                            ("HIGH_VOLATILITY", "High Volatility/Choppy"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gpt_regime_classification",
                    models.TextField(help_text="Raw reasoning from GPT-5.5"),
                ),
                (
                    "risk_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TradeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        help_text="MT5 Deal/Order Ticket ID", max_length=50, unique=True
                    ),
                ),
                ("symbol", models.CharField(default="XAUUSD", max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("lots", models.DecimalField(decimal_places=2, max_digits=6)),
                ("entry_price", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Groq Scalper confidence %",
                        max_digits=5,
                    ),
                ),
                (
                    "raw_groq_response",
                    models.JSONField(
                        help_text="Complete JSON response block from the Groq LLM"
                    ),
                ),
                (
                    "feature_snapshot",
                    models.JSONField(
                        help_text="The normalized data matrix sent to Groq (ATR, Close arrays, etc.)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
