# Generated by Django 6.0.6 on 2026-07-14 14:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alpha_engine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("symbol", models.CharField(default="XAUUSD", max_length=20)),
                ("current_price", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "rsi_14",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "atr_14",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "market_regime",
                    models.CharField(
                        choices=[
                            ("TRENDING_UP", "Trending Up"),
                            ("TRENDING_DOWN", "Trending Down"),
                            ("RANGING", "Ranging/Bound"),
                            ("HIGH_VOLATILITY", "High Volatility/Choppy"),
                            ("BULL_CLIMAX", "Bullish Climax"),
                            ("BEAR_CLIMAX", "Bearish Climax"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "gpt_regime_classification",
                    models.TextField(
                        blank=True,
                        help_text="Raw reasoning from the AI engine",
                        null=True,
                    ),
                ),
                (
                    "risk_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=4),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TradeMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_id",
                    models.CharField(
                        blank=True,
                        help_text="MT5 Deal/Order Ticket ID",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("symbol", models.CharField(default="XAUUSD", max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("HOLD", "Hold"),
                            ("CLOSE", "Close"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed execution"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("lots", models.DecimalField(decimal_places=2, max_digits=6)),
                ("entry_price", models.DecimalField(decimal_places=5, max_digits=10)),
                (
                    "exit_price",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Groq Scalper confidence %",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ai_reasoning",
                    models.TextField(
                        help_text="Decisions details and execution thesis"
                    ),
                ),
                (
                    "raw_groq_response",
                    models.JSONField(
                        blank=True,
                        help_text="Complete JSON response block from the Groq LLM",
                        null=True,
                    ),
                ),
                (
                    "feature_snapshot",
                    models.JSONField(
                        blank=True,
                        help_text="The normalized data matrix sent to Groq",
                        null=True,
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "market_state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="alpha_engine.marketstate",
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.DeleteModel(
            name="MarketRegime",
        ),
        migrations.DeleteModel(
            name="TradeLog",
        ),
    ]
